# Message type "enum"
uint8 MESSAGE_TYPE_INSTALLED_POSITION = 0
uint8 MESSAGE_TYPE_CURRENT_POSITION = 1

uint8 message_type      # See above
---
bool status
int32 longitude
int32 latitude
int32 altitude
